### ISSUE TITLE
Not picking Cuda

### ISSUE THREAD

**Issue by mukeshsnp12** [harisreedhar/Swap-Mukham#10]
I have cuda 11.8 installed with onnxruntime-gpu 1.15.0
But it is not using my gpu rtx 3070

**Comment by harisreedhar** [comment]
@mukeshsnp12  have you installed pytorch with cuda?

**Comment by mukeshsnp12** [comment]
Yes

**Comment by mukeshsnp12** [comment]
Name: torch
Version: 2.0.1+cu118
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: c:\users\mukes\appdata\roaming\python\python310\site-packages
Requires: filelock, jinja2, networkx, sympy, typing-extensions
Required-by: accelerate, basicsr, facexlib, fairscale, gfpgan, koila, lightning, pytorch-lightning, realesrgan, so-vits-svc-fork, timm, torchaudio, torchcrepe, torchmetrics, torchvision, xformers

**Comment by mukeshsnp12** [comment]
C:\Users\mukes\AppData\Roaming\Python\Python310\site-packages\torchvision\transforms\functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
Running on local URL:  http://127.0.0.1:7860

**Comment by harisreedhar** [comment]
No idea bro, i'm on linux don't know why it happens on windows 😪. You may try uninstalling ``onnxruntime-gpu==1.15`` and install ``onnxruntime==1.15``. Not sure though.

**Comment by harisreedhar** [comment]
> C:\Users\mukes\AppData\Roaming\Python\Python310\site-packages\torchvision\transforms\functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
>   warnings.warn(
> Running on local URL:  http://127.0.0.1:7860

Those warnings can be ignored

**Comment by mukeshsnp12** [comment]
Working now, I installed roop too and then also uninstalled onnx and reinstalled. now working on gpu

**Comment by harisreedhar** [comment]
@mukeshsnp12 can u share your steps along with ``conda list`` or ``pip freeze`` output? It could be helpful for other people having same issue.

**Comment by mukeshsnp12** [comment]
I cloned roop in roop directory
git clone https://github.com/s0md3v/roop
cd roop
pip install -r requirements.txt

pip uninstall onnxruntime onnxruntime-gpu
pip install onnxruntime-gpu==1.15.0

I uninstalled onnxruntime maybe twice or thrice and it worked. 
I deleted roop and I am working on Swap-Mukham gui. It's good and easy.

**Comment by harisreedhar** [comment]
Thank you

**Comment by mukeshsnp12** [comment]
Much appreciated and lot of thanks.
